
import { Reciter } from '../types';

export const RECITER_SERVERS: Record<string, string> = {
  qaudio: "https://download.quranicaudio.com/quran/",
  muqri: "https://muqri.com/audio/",
  iweb: "http://audio3.islamweb.net/quran/",
  mp3quran6: "https://server6.mp3quran.net/",
  mp3quran7: "https://server7.mp3quran.net/",
  mp3quran8: "https://server8.mp3quran.net/",
  mp3quran9: "https://server9.mp3quran.net/",
  mp3quran10: "https://server10.mp3quran.net/",
  mp3quran11: "https://server11.mp3quran.net/",
  mp3quran12: "https://server12.mp3quran.net/",
  mp3quran13: "https://server13.mp3quran.net/",
  mp3quran14: "https://server14.mp3quran.net/"
};

export const QIRAAT_NAMES: Record<number, string> = {
  0: "حفص عن عاصم", // Default implied
  1: "ورش عن نافع",
  2: "قالون عن نافع",
  4: "الدوري عن أبي عمرو",
  5: "السوسي عن أبي عمرو",
  7: "ابن ذكوان عن ابن عامر",
  8: "شعبة عن عاصم",
  9: "خلف عن حمزة",
  10: "خلف عن حمزة", // Alternate mapping
  12: "أبو الحارث عن الكسائي",
  13: "الدوري عن الكسائي"
};

// Extracted from the provided code
export const RECITERS_LIST: Reciter[] = [
  {en:"Mahmoud Khalil al-Husari",ar:"محمود خليل الحصري",recitations:[{loc:"muqri:alhusari/mp3"},{tags:"إذاعة",loc:"qaudio:mahmood_khaleel_al-husaree_iza3a"},{qiraah:4,loc:"qaudio:mahmood_khaleel_al-husaree_doori"}]},
  {en:"AbdulBaset AbdulSamad",ar:"عبد الباسط عبد الصمد",recitations:[{loc:"qaudio:abdul_basit_murattal"},{tags:"مجود",loc:"muqri:abdulbasit-m/mp3"},{qiraah:1,loc:"qaudio:abdulbaset_warsh"}]},
  {en:"Abdullah Ali Jabir",ar:"عبد الله علي جابر",recitations:[{loc:"qaudio:abdullaah_alee_jaabir_studio"},{tags:"تراويح",loc:"qaudio:abdullaah_alee_jaabir"}]},
  {en:"Abdullah Basfar",ar:"عبد الله بصفر",recitations:[{loc:"qaudio:abdullaah_basfar"}]},
  {en:"Abu Bakr al-Shatri",ar:"أبو بكر الشاطرى",recitations:[{loc:"muqri:alshatiri/mp3"},{tags:"تراويح",loc:"qaudio:abu_bakr_ash-shatri_tarawee7"}]},
  {en:"Sa'ud ash-Shuraym",ar:"سعود الشريم",recitations:[{loc:"qaudio:sa3ood_al-shuraym"}]},
  {en:"Saad al-Ghamdi",ar:"سعد الغامدي",recitations:[{loc:"muqri:alghamidi/mp3"}]},
  {en:"Muhammad Ayyoob",ar:"محمد أيوب",recitations:[{loc:"muqri:mayyub/mp3"},{tags:"تراويح",loc:"qaudio:muhammad_ayyoob_hq"}]},
  {en:"Muhammad Siddiq al-Minshawi",ar:"محمد صديق المنشاوي",recitations:[{loc:"muqri:alminshawi/mp3"},{tags:"مجود",loc:"qaudio:minshawi_mujawwad"}]},
  {en:"Maher al-Muayqili",ar:"ماهر المعيقلى",recitations:[{loc:"qaudio:maher_256"}]},
  {en:"Abdur-Rahman as-Sudais",ar:"عبد الرحمن السديس",recitations:[{loc:"qaudio:abdurrahmaan_as-sudays"}]},
  {en:"Ali al-Huthaifi",ar:"علي الحذيفي",recitations:[{loc:"muqri:alhuthayfi/mp3"},{qiraah:0,loc:"qaudio:huthayfi_qaloon"}]},
  {en:"Ibrahim al-Akhdar",ar:"إبراهيم الأخضر",recitations:[{loc:"qaudio:ibrahim_al_akhdar"}]},
  {en:"Idrees Abkar",ar:"إدريس أبكر",recitations:[{loc:"qaudio:idrees_akbar"}]},
  {en:"Khalid al-Qahtani",ar:"خالد القحطاني",recitations:[{loc:"qaudio:khaalid_al-qahtaanee",tags:"تراويح"}]},
  {en:"Nasser al-Qatami",ar:"ناصر القطامي",recitations:[{loc:"qaudio:nasser_bin_ali_alqatami"}]},
  {en:"Tawfeeq as-Sa'igh",ar:"توفيق الصائغ",recitations:[{loc:"qaudio:tawfeeq_bin_saeed-as-sawaaigh"}]},
  {en:"Salah Bukhatir",ar:"صلاح بوخاطر",recitations:[{loc:"qaudio:salaah_bukhaatir"}]},
  {en:"Khalifah al-Tunayji",ar:"خليفة الطنيجي",recitations:[{loc:"mp3quran12:tnjy"}]},
  {en:"Ahmed al-Ajmi",ar:"أحمد العجمي",recitations:[{loc:"qaudio:ahmed_ibn_3ali_al-3ajamy"}]},
  {en:"AbdulAzeez al-Ahmad",ar:"عبد العزيز الأحمد",recitations:[{loc:"qaudio:abdulazeez_al-ahmad"}]},
  {en:"AbdulBari ath-Thubaiti",ar:"عبد الباري الثبيتي",recitations:[{loc:"qaudio:thubaity"}]},
  {en:"AbdulKareem al-Hazmi",ar:"عبد الكريم الحازمي",recitations:[{loc:"qaudio:abdulkareem_al_hazmi"}]},
  {en:"AbdulMuhsin al-Qasim",ar:"عبد المحسن القاسم",recitations:[{loc:"qaudio:abdul_muhsin_alqasim"}]},
  {en:"AbdulWadood Haneef",ar:"عبد الودود حنيف",recitations:[{loc:"qaudio:abdulwadood_haneef"},{tags:"نادر",loc:"qaudio:abdul_wadood_haneef_rare"}]},
  {en:"Abdullah Awad al-Juhani",ar:"عبد الله عواد الجهني",recitations:[{loc:"qaudio:abdullaah_3awwaad_al-juhaynee"}]},
  {en:"Abdullah Khayat",ar:"عبد الله خياط",recitations:[{loc:"qaudio:khayat"}]},
  {en:"Abdullah Matroud",ar:"عبد الله المطرود",recitations:[{loc:"qaudio:abdullah_matroud"}]},
  {en:"Abdur-Rashid Sufi",ar:"عبد الرشيد صوفي",recitations:[{loc:"qaudio:abdurrashid_sufi"},{qiraah:4,loc:"qaudio:abdurrashid_sufi_doori"},{qiraah:5,loc:"qaudio:abdurrashid_sufi_soosi_rec"},{qiraah:8,loc:"qaudio:abdurrashid_sufi_shu3ba"},{qiraah:10,loc:"qaudio:abdurrashid_sufi_-_khalaf_3an_7amza_recitation"},{qiraah:12,loc:"qaudio:abdurrashid_sufi_abi_al7arith"}]},
  {en:"Adel Kalbani",ar:"عادل الكلباني",recitations:[{loc:"qaudio:adel_kalbani"}]},
  {en:"Ahmad Nauina",ar:"أحمد نعينع",recitations:[{loc:"qaudio:ahmad_nauina"}]},
  {en:"Akram al-Alaqmi",ar:"أكرم العلاقمي",recitations:[{loc:"qaudio:akram_al_alaqmi"}]},
  {en:"Al-Hussayni al-'Azazi",ar:"الحسيني العزازي",recitations:[{loc:"qaudio:alhusaynee_al3azazee_with_children",tags:"معلم"}]},
  {en:"Ali Hajjaj Alsouasi",ar:"علي حجاج السويسي",recitations:[{loc:"qaudio:ali_hajjaj_alsouasi"}]},
  {en:"Aziz Alili",ar:"عزيز عليلى",recitations:[{loc:"qaudio:aziz_alili"}]},
  {en:"Bandar Baleela",ar:"بندر بليلة",recitations:[{loc:"qaudio:bandar_baleela"}]},
  {en:"Fares Abbad",ar:"فارس عباد",recitations:[{loc:"qaudio:fares"}]},
  {en:"Hani ar-Rifai",ar:"هاني الرفاعي",recitations:[{loc:"qaudio:rifai"}]},
  {en:"Hatem Farid",ar:"حاتم فريد",recitations:[{loc:"qaudio:hatem_farid/collection"}]},
  {en:"Ibrahim al-Jibrin",ar:"إبراهيم الجبرين",recitations:[{loc:"qaudio:jibreen"}]},
  {en:"Mahmood Ali al-Bana",ar:"محمود علي البنا",recitations:[{loc:"qaudio:mahmood_ali_albana"}]},
  {en:"Mohammad al-Tablawi",ar:"محمد الطبلاوي",recitations:[{loc:"qaudio:mohammad_altablawi"}]},
  {en:"Muhammad Jibreel",ar:"محمد جبريل",recitations:[{loc:"qaudio:muhammad_jibreel/complete"}]},
  {en:"Muhammad al-Luhaidan",ar:"محمد اللحيدان",recitations:[{loc:"qaudio:muhammad_alhaidan"}]},
  {en:"Muhammad al-Mehysni",ar:"محمد المحيسني",recitations:[{loc:"qaudio:mehysni"}]},
  {en:"Nabil ar-Rifai",ar:"نبيل الرفاعي",recitations:[{loc:"qaudio:nabil_rifa3i"}]},
  {en:"Sadaqat 'Ali",ar:"صدقات علي",recitations:[{loc:"qaudio:sadaqat_ali"}]},
  {en:"Sahl Yasin",ar:"سهل ياسين",recitations:[{loc:"qaudio:sahl_yaaseen"}]},
  {en:"Salah al-Hashim",ar:"صلاح الهاشم",recitations:[{loc:"qaudio:salah_alhashim"}]},
  {en:"Salah al-Budair",ar:"صلاح البدير",recitations:[{loc:"qaudio:salahbudair"}]},
  {en:"Saleh aal Taleb",ar:"صالح آل طالب",recitations:[{loc:"qaudio:saleh_al_taleb"}]},
  {en:"Wadee al-Yamani",ar:"وديع اليمني",recitations:[{loc:"qaudio:wadee_hammadi_al-yamani"}]},
  {en:"Yasser ad-Dussari",ar:"ياسر الدوسري",recitations:[{loc:"qaudio:yasser_ad-dussary"}]},
  {en:"Ahmad al-Hawashi",ar:"أحمد الحواشي",recitations:[{loc:"mp3quran11:hawashi"}]},
  {en:"Ahmad al-Trabulsi",ar:"أحمد الطرابلسي",recitations:[{loc:"mp3quran10:trabulsi",qiraah:9},{loc:"mp3quran10:trablsi",qiraah:0}]},
  {en:"Ahmad Sabir",ar:"أحمد صابر",recitations:[{loc:"mp3quran8:saber"}]},
  {en:"Ahmad Aamer",ar:"أحمد عامر",recitations:[{loc:"mp3quran10:Aamer"}]},
  {en:"Ibrahim al-Doosari",ar:"إبراهيم الدوسري",recitations:[{loc:"mp3quran10:ibrahim_dosri_hafs",qiraah:9},{loc:"mp3quran10:ibrahim_dosri_warsh",qiraah:1}]},
  {en:"Aldawkali Muhammad al-'aalm",ar:"الدوكالي محمد العالم",recitations:[{loc:"mp3quran7:dokali",qiraah:0}]},
  {en:"Alzin Muhammad Ahmad",ar:"الزين محمد أحمد",recitations:[{loc:"mp3quran9:alzain"}]},
  {en:"Aluyoon al-Kooshi",ar:"العيون الكوشي",recitations:[{loc:"mp3quran11:koshi",qiraah:1}]},
  {en:"Alfath Muhammad al-Zubayr",ar:"الفاتح محمد الزبير",recitations:[{loc:"mp3quran6:fateh",qiraah:4}]},
  {en:"Alqari Yasin",ar:"القارئ ياسين",recitations:[{loc:"mp3quran11:qari",qiraah:1}]},
  {en:"Jamal Shakir Abdullah",ar:"جمال شاكر عبد الله",recitations:[{loc:"mp3quran6:jamal"}]},
  {en:"Jam'aan al-Usaymi",ar:"جمعان العصيمي",recitations:[{loc:"mp3quran6:jaman"}]},
  {en:"Khaled al-Muhanna",ar:"خالد المهنا",recitations:[{loc:"mp3quran11:mohna"}]},
  {en:"Khaled Abdul-Kafi",ar:"خالد عبد الكافي",recitations:[{loc:"mp3quran11:kafi"}]},
  {en:"Rami al-D'ais",ar:"رامي الدعيس",recitations:[{loc:"mp3quran6:rami"}]},
  {en:"Zaki Daghstani",ar:"زكي داغستاني",recitations:[{loc:"mp3quran9:zaki"}]},
  {en:"Sayyid Ramadhan",ar:"سيد رمضان",recitations:[{loc:"mp3quran12:sayed"}]},
  {en:"Shirzad Abdul-Rahman tahr",ar:"شيرزاد عبد الرحمن طاهر",recitations:[{loc:"mp3quran12:taher"}]},
  {en:"Sabr Abdul-Hakam",ar:"صابر عبد الحكم",recitations:[{loc:"mp3quran12:hkm"}]},
  {en:"Tariq Abdul-Ghani da'oob",ar:"طارق عبد الغني دعوب",recitations:[{loc:"mp3quran10:tareq",qiraah:0}]},
  {en:"Adil Rayan",ar:"عادل ريان",recitations:[{loc:"mp3quran8:ryan"}]},
  {en:"Abdul-Bari Muhammad",ar:"عبد البارئ محمد",recitations:[{loc:"mp3quran12:bari"}]},
  {en:"Abdul-Rahman al-'uoosi",ar:"عبد الرحمن العوسي",recitations:[{loc:"mp3quran6:aloosi"}]},
  {en:"Abdul-Rahman al-Majd",ar:"عبد الرحمن الماجد",recitations:[{loc:"mp3quran10:a_majed"}]},
  {en:"Abdullah al-Khalaf",ar:"عبد الله الخلف",recitations:[{loc:"mp3quran14:khalf"}]},
  {en:"Abdullah al-Kandri",ar:"عبد الله الكندري",recitations:[{loc:"mp3quran10:Abdullahk"}]},
  {en:"Abdul-Muhsin al-Harithi",ar:"عبد المحسن الحارثي",recitations:[{loc:"mp3quran6:mohsin_harthi"}]},
  {en:"Abdul-Muhsin al-'Ubaykan",ar:"عبد المحسن العبيكان",recitations:[{loc:"mp3quran12:obk"}]},
  {en:"Abdul-Hadi Ahmad knakri",ar:"عبد الهادي أحمد كناكري",recitations:[{loc:"mp3quran6:kanakeri"}]},
  {en:"Umar al-Qazabiri",ar:"عمر القزابري",recitations:[{loc:"mp3quran9:omar_warsh",qiraah:1}]},
  {en:"Maher Shakhashero",ar:"ماهر شخاشيرو",recitations:[{loc:"mp3quran10:shaksh"}]},
  {en:"Muhammad Rashad al-Sharif",ar:"محمد رشاد الشريف",recitations:[{loc:"mp3quran10:rashad"}]},
  {en:"Muhammad salh 'aalm shah",ar:"محمد صالح عالم شاه",recitations:[{loc:"mp3quran12:shah"}]},
  {en:"Abdul-Hakim Saeed aal Abdullah",ar:"عبد الحكيم سعيد آل عبد الله",recitations:[{loc:"mp3quran12:abdullah_dori",qiraah:13},{loc:"mp3quran9:abdullah",qiraah:"البزي وقنبل"}]},
  {en:"Muhammad Uthman khan",ar:"محمد عثمان خان",recitations:[{loc:"mp3quran6:khan"}]},
  {en:"Mahmood al-Rifa'ai",ar:"محمود الرفاعي",recitations:[{loc:"mp3quran11:mrifai"}]},
  {en:"Mahmood al-Shimi",ar:"محمود الشيمي",recitations:[{loc:"mp3quran10:sheimy",qiraah:13}]},
  {en:"Mustafa al-Lahwani",ar:"مصطفى اللاهوني",recitations:[{loc:"mp3quran6:lahoni"}]},
  {en:"Muaydh al-Harthi",ar:"معيض الحارثي",recitations:[{loc:"mp3quran8:harthi"}]},
  {en:"Miftah al-Sltni",ar:"مفتاح السلطني",recitations:[{loc:"mp3quran11:muftah_thakwan",qiraah:7},{loc:"mp3quran9:sultany",qiraah:4},{loc:"mp3quran10:muftah",qiraah:9},{loc:"mp3quran6:saltany_kisaia",qiraah:13}]},
  {en:"Musa Bilal",ar:"موسى بلال",recitations:[{loc:"mp3quran11:bilal"}]},
  {en:"Nimah al-Hasan",ar:"نعمة الحسان",recitations:[{loc:"mp3quran8:namh"}]},
  {en:"Walid al-Naihi",ar:"وليد النائحي",recitations:[{loc:"mp3quran9:waleed",qiraah:"قالون ط أبي نشيط"}]},
  {en:"Yasir al-Qurashi",ar:"ياسر القرشي",recitations:[{loc:"mp3quran9:qurashi"}]},
  {en:"Yasir al-Mazroo'iee",ar:"ياسر المزروعي",recitations:[{loc:"mp3quran9:mzroyee",qiraah:"رويس وروح"}]},
  {en:"Yahya Hawa",ar:"يحيى حوى",recitations:[{loc:"mp3quran12:yahya"}]},
  {en:"Yusuf al-Shawayiee",ar:"يوسف الشويعي",recitations:[{loc:"mp3quran9:yousef"}]},
  {en:"Yusuf ibn Nuh Ahmad",ar:"يوسف بن نوح أحمد",recitations:[{loc:"mp3quran8:noah"}]}
];
